- name: CREATE VM PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    vmname: ansiblevm
    resgrp: lrich-RG
    
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resgrp }}"
      location: eastus
      state: present
      
  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      account_type: Standard_LRS
      
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      address_prefixes: "10.10.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      address_prefix: "10.10.0.0/24"
      virtual_network: '{{ vmname }}'

  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: '{{ resgrp }}'
      allocation_method: Static
      name: '{{ vmname }}'
      
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      virtual_network: '{{ vmname }}'
      subnet: '{{ vmname }}'
      public_ip_name: '{{ vmname }}'
      security_group: '{{ vmname }}'

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      storage_account: '{{ vmname }}'
      storage_container: '{{ vmname }}'
      vm_size: Standard_A0
      admin_username: lrich
      ssh_password_enabled: False
      ssh_public_keys: 
        - path: /home/lrich/.ssh/authorized_keys
          key_data: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwxwsGbmfMcDGJGPPJqJNxI+cuu4nKYjTHIVoMTMYyiDHh4aSm710nL0mHeWjAe8VF6Gzw8asF7t3HSTv7lQ8d6qDE9iKELHUO2ZCo6Aw8SLzdUmS4M8X4x69iOWGHhcDhVlWyrqypwyoS+EIq3ACx4d/lnRUdT/xEHRjVyf989W5AsBkH90BiJnpXz5LXVfcl9JAzY/GjINZc2BzpyrzbUI4cVwIfXiXTHNWwpyN+tb3UqHl0Y9ZtwIIB1KgroJP/C/li4YrNxBSassNFow0HAATAo2UwZeE8d0IWk5Pv9QOSYXKblLgLvbxQRnuNfH+pvcOA0HYC05dXh5AwcRnn lrich@lrich-OSX.local'
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.2'
        version: latest
